### ISSUE TITLE
Update Claim, Result according to spec

### ISSUE THREAD

**Issue by vdice** [cnabio/cnab-go#202]
The Claim and Result objects need to be updated per the latest working version of the Claim spec.

It may be wise to wait for https://github.com/cnabio/cnab-spec/pull/349 to merge and a tag cut with these updates included.

When updating, assuming https://github.com/cnabio/cnab-go/pull/188 is in by then, bump the `CNABSpecVersion` in `claim/claim.go` and unskip the `TestClaimSchema` test in `claim/claim_test.go`.

Then, run `make fetch-schemas test` which will fetch the claim schema based on the updated spec version and run the tests.

**Comment by carolynvs** [comment]
@vdice Can this be closed?

**Comment by vdice** [comment]
Yes!  Closing.
