### ISSUE TITLE
Add Parameter Set

### ISSUE THREAD

**Issue by vdice** [cnabio/cnab-go#230]
[Porter](https://porter.sh) implemented Parameter Sets, a correlate for parameters to the Credential Set originally defined in the cnab-spec repo and its golang implementation existing here in this repo.  This issue is therefore around migrating the re-usable Parameter Set definition(s) and methods into this library for the broader community to use.

- [ ] Migrate Parameter Set definition and methods into this repo.  See https://github.com/deislabs/porter/blob/main/pkg/parameters/parameterset.go and other applicable logic (like storage) in https://github.com/deislabs/porter/tree/main/pkg/parameters

- [ ] Add a `SchemaVersion` field to the imported Parameter Set struct like was done for Credential Sets in https://github.com/cnabio/cnab-go/pull/229 so implementations can pin to a known version of a Parameter Set definition.  This will necessitate adding a section to the cnab-spec repo similar to https://github.com/cnabio/cnab-spec/blob/master/802-credential-sets.md and/or the addition in the same repo of a json schema definition.

**Comment by carolynvs** [comment]
It seems to me that unless we change the schema for credentialsets to be generic, there will need to be two schema: one for each. So parameters' schemaVersion would be `cnab-parametersets-1.0.0-DRAFT-*` and credentials would be `cnab-credentialsets-1.0.0-DRAFT-*`.

I'm not sure consolidating them together and causing the breaking change for such little value is worth it.

**Comment by vdice** [comment]
I started on this but realized we'd want to get https://github.com/cnabio/cnab-go/pull/229 in first.  (Porter currently references code from the branch in 229, including some of the files intended for porting over to this library.)

**Comment by carolynvs** [comment]
Closing since we've since changed direction about putting non-runtime concerns into cnab-go.
