### ISSUE TITLE
Require only one review for pull requests to the cnab-go library

### ISSUE THREAD

**Issue by carolynvs** [cnabio/cnab-go#258]
We are having a hard time lately getting pull request reviews in a reasonable amount of time. @vdice and I discussed this in today's CNAB meeting and would like to propose that we only require a single review in this repository (spec still gets 2 reviews).

Would the maintainers please reply with a +1 if you agree?

**Comment by technosophos** [comment]
+1 - We have definitely done this in the past with other projects in order to fine-tune velocity. In this case, I think it is 💯 justified.

**Comment by carolynvs** [comment]
@technosophos How many votes do you think we need to make the change? So far we have you, myself, Radu, and Vaughn voting in favor.

**Comment by technosophos** [comment]
I would imagine simple majority would do.

**Comment by carolynvs** [comment]
Ok, there are 8 people in the codeowners file, so just 1 more to go! 🍿

**Comment by glyn** [comment]
+1

**Comment by chris-crone** [comment]
SGTM!

**Comment by scottbuckel** [comment]
+1!

**Comment by silvin-lubecki** [comment]
LGTM 👍

**Comment by carolynvs** [comment]
I'll update the GitHub settings to only require a single review. So say we all. Thanks everyone!
