### ISSUE TITLE
[spec compliance] Implement Outputs in Kubernetes Driver

### ISSUE THREAD

**Issue by jeremyrickard** [cnabio/cnab-go#73]
Now that we have mostly added all the relevant output definitions and claims elements, we should complete the picture and implement output handling in the Kubernetes driver. The Kubernetes driver currently handles placing parameter and credentials into files for the invocation image, so we should extend the driver to handle obtaining them from the invocation image, maybe by adding a volume to store the outputs and reading from that? 

I think we should leave _what happens_ to them after they are read from the invocation image up to the end tooling, but we should make the driver able to fetch them.

**Comment by astrieanna** [comment]
We summarized our thoughts on implementation options for the k8s driver here: https://github.com/deislabs/duffle/issues/747#issuecomment-512048160
